name: iShop
main: com.minedhype.ishop.iShop
description: Item trading shops with unique GUI!
author: Beez0r
website: https://minedhype.com
version: "${project.version}"
api-version: "1.14"
softdepend: [Vault, WorldGuard]
commands:
  ishop:
    description: "/shop"
    aliases: [shop]
